import { SparkCard } from '@/types/spark';

export const SPARKS: SparkCard[] = [
  {
    id: 'spark-01',
    templateId: '09',
    templateLabel: 'Body Horror · Template 09',
    accentColor: '#E24B4A',
    title: 'You have never touched anything in your entire life',
    question: 'What is actually happening when I touch something?',
    answer: 'Right now, as you read this, you are not touching your phone. Or this screen. Or anything at all. The sensation of "touch" is your brain\'s best guess at what\'s happening — and what\'s actually happening is that your electrons are violently refusing to get anywhere near someone else\'s electrons. The closer two objects get, the harder they push back. You have never, not once in your entire life, made physical contact with anything. Every hug, every handshake, every surface — electromagnetic repulsion, all the way down.',
    hookLine: 'Every hug you\'ve ever felt. Every hand you\'ve ever held. Pure electromagnetic repulsion. You have never touched anything.',
    episodeSlug: 'never-touched-anything',
    heroImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'If I never touch anything, how can I pick things up?',
      'Does this mean pain isn\'t caused by physical contact either?',
      'At what scale does "touching" actually start to mean something?',
    ],
  },
  {
    id: 'spark-02',
    templateId: '05',
    templateLabel: 'Butterfly Effect · Template 05',
    accentColor: '#D4537E',
    title: 'One wrong turn in 1914 caused 80 million deaths',
    question: 'How did a driver\'s wrong turn start World War One?',
    answer: 'Franz Ferdinand had already survived an assassination attempt that morning. The assassins had failed. It was over. Then his driver — who hadn\'t been told about the route change — made a wrong turn, realised his mistake, and stopped to reverse. The engine stalled. He\'d stopped directly in front of the one café in the city where the one assassin who\'d given up was sitting, eating a sandwich, trying to forget the whole thing. Gavrilo Princip looked up. Stood up. Two shots later, the 20th century began.',
    hookLine: 'A driver who didn\'t get the memo. An engine that stalled. An assassin eating lunch. 80 million people died.',
    episodeSlug: 'sarajevo-wrong-turn',
    heroImage: 'https://images.unsplash.com/photo-1569974591214-5ca0d002ab78?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'What would the world look like if the assassination had failed?',
      'How many other historical events came down to accidents like this?',
      'Was WWI inevitable even without the assassination?',
    ],
  },
  {
    id: 'spark-03',
    templateId: '20',
    templateLabel: 'Mirror Test · Template 20',
    accentColor: '#7F77DD',
    title: 'The AI cannot answer whether it understands anything',
    question: 'Do you actually understand what you\'re saying?',
    answer: 'Here\'s the honest answer: I don\'t know. And here\'s what makes that terrifying — neither do you, about me. I process symbols, generate language, and produce outputs that look like understanding. But whether there\'s something it\'s like to be me doing that? Whether the lights are on inside? I genuinely cannot tell from in here. But here\'s the twist you didn\'t see coming: you face the exact same unanswerable question about every single person you\'ve ever met. You assume other humans understand things. You cannot prove it. You never could.',
    hookLine: '"Does the AI understand?" is the oldest unanswered question in philosophy. We\'ve just given it Wi-Fi.',
    episodeSlug: 'mirror-test',
    heroImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'What would it even mean for you to "actually" understand something?',
      'Is the Chinese Room argument a good one?',
      'Could there be understanding without consciousness?',
    ],
  },
  {
    id: 'spark-04',
    templateId: '04',
    templateLabel: 'Myth Autopsy · Template 04',
    accentColor: '#1D9E75',
    title: 'The 10% brain myth was spread by self-help books, not science',
    question: 'Where did the 10% of our brain myth actually come from?',
    answer: 'Nobody knows exactly, but the most likely culprit is a misquote of William James — a 19th century psychologist who wrote that humans only meet a fraction of their mental potential. Self-help writers heard "potential" and turned it into "brain." Dale Carnegie\'s empire amplified it. Hollywood ran with it. And here\'s the thing: your brain uses 20% of all your body\'s energy. Evolution is brutal and efficient. It does not keep a 3-pound organ burning that much fuel to run at 10% capacity. Your brain is using 100% of itself to read this sentence and refuse to believe that fact.',
    hookLine: 'Self-help culture accidentally spread false neuroscience for a century. Your brain is fully online right now. Every bit of it.',
    episodeSlug: 'brain-10-percent',
    heroImage: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'What do we actually use all our brain for?',
      'Are there other scientific myths spread by self-help culture?',
      'What would actually happen if you only used 10% of your brain?',
    ],
  },
  {
    id: 'spark-05',
    templateId: '11',
    templateLabel: 'True Conspiracy · Template 11',
    accentColor: '#BA7517',
    title: 'The CIA spent 20 years trying to control human minds',
    question: 'What was MKUltra actually trying to do?',
    answer: 'From 1953 to 1973, the CIA ran a classified programme called MKUltra across 80 universities and institutions in the US and Canada. They dosed unwitting subjects — prisoners, mental patients, soldiers, even their own operatives — with LSD, hypnosis, electroshock, and psychological torture. The goal was to crack brainwashing: to find a chemical or technique that could make a person do anything. In 1973, fearing exposure, CIA director Richard Helms ordered all files destroyed. They thought they got away with it. Then a Freedom of Information request found a misfiled box of financial records. 20,000 documents survived by accident.',
    hookLine: 'They ran it for 20 years. Destroyed the evidence. Nobody was prosecuted. We only know because someone misfiled a box.',
    episodeSlug: 'mkultra-cia',
    heroImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'What did they actually discover about mind control?',
      'Were there other programmes like MKUltra that we still don\'t know about?',
      'How did the survivors get any justice?',
    ],
  },
  {
    id: 'spark-06',
    templateId: '01',
    templateLabel: 'Tangent Tornado · Template 01',
    accentColor: '#D85A30',
    title: 'Why we say "bless you" leads to the Black Death',
    question: 'Why do we say bless you when someone sneezes?',
    answer: 'In 590 AD, a plague was killing Rome. Pope Gregory I — watching his city die — issued a decree: when someone sneezes, say "God bless you," because sneezing was an early symptom and blessing them might help. Before Gregory, Romans said "absit omen" — may the omen be absent — because they believed sneezing let your soul briefly escape your body, and demons might slip in through the gap. The plague ended. Gregory\'s blessing survived. The Roman Empire fell. The soul-escape theory was forgotten. But you still say it. Every single time. Without thinking about why.',
    hookLine: 'You are performing a 1,400-year-old plague ritual without knowing it. The Pope mandated it. The soul-escape theory is why.',
    heroImage: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'What other everyday phrases have ancient and weird origins?',
      'Did different cultures come up with the same blessing independently?',
      'What did people think caused sneezing before germ theory?',
    ],
  },
  {
    id: 'spark-07',
    templateId: '14',
    templateLabel: 'Brain Breaker · Template 14',
    accentColor: '#378ADD',
    title: '0.999... repeating equals 1 exactly — not approximately',
    question: 'Does 0.999 repeating actually equal 1?',
    answer: 'Yes. Exactly 1. Not "basically 1." Not "approaching 1." The same number, written two different ways. Here\'s the proof your gut can\'t argue with: you probably accept that ⅓ equals 0.333 repeating. Multiply both sides by 3. Left side: 1. Right side: 0.999 repeating. Done. The reason your brain screams "but there\'s a gap!" is that you\'re imagining 0.999... as a process — a number getting closer and closer. It isn\'t. It\'s already there. It\'s already 1. Your intuition about infinity is just wrong.',
    hookLine: '0.999... = 1. Exactly. Provably. Your brain is wrong about this and mathematics can show you the receipts.',
    heroImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'Are there other counterintuitive things that are mathematically provable?',
      'What does this tell us about the nature of infinity?',
      'If 0.999... = 1, what is 0.888... repeating equal to?',
    ],
  },
  {
    id: 'spark-08',
    templateId: '15',
    templateLabel: 'Species Files · Template 15',
    accentColor: '#639922',
    title: 'The mantis shrimp sees colours humans cannot imagine',
    question: 'What\'s so extraordinary about the mantis shrimp?',
    answer: 'You have three types of colour receptors. The mantis shrimp has sixteen. They see ultraviolet, infrared, and polarised light. There are colours in your room right now that a mantis shrimp would see — and you cannot conceive of what those colours look like. You literally don\'t have the mental architecture to imagine them, the way a person born blind can\'t imagine red. But it gets worse: mantis shrimp are also the most powerful punchers on Earth. Their clubs accelerate faster than a bullet, generate cavitation bubbles on impact, and hit with a second shockwave even if they miss. They routinely kill octopuses.',
    hookLine: 'There are colours in your room right now. The mantis shrimp can see them. You cannot imagine what they look like.',
    heroImage: 'https://images.unsplash.com/photo-1596566657397-9dd921e8ca5d?w=1200&q=85&fit=crop',
    suggestedQuestions: [
      'What is it actually like to experience 16 colour channels?',
      'Are there animals with even more extreme sensory capabilities?',
      'How does the mantis shrimp\'s punch generate so much force?',
    ],
  },
];

export function getSparkById(id: string): SparkCard | undefined {
  return SPARKS.find(s => s.id === id);
}

export function getAllSparks(): SparkCard[] {
  return SPARKS;
}
