import type { Topic, TopicId } from '@/types/topics';

export const TOPICS: Topic[] = [
  // ── Knowledge & wonder ─────────────────────────────────────────
  {
    id: 'science',
    name: 'Science',
    description: 'Where the universe keeps surprising us.',
    registers: ['awe', 'surprise', 'education'],
    accentId: 'sage',
    sources: ['arxiv', 'reddit_science', 'naturepicks', 'phys_org'],
    searchTerms: ['discovery', 'research', 'findings', 'breakthrough'],
  },
  {
    id: 'space',
    name: 'Space',
    description: 'Everything happening outside the thin shell we live in.',
    registers: ['awe', 'surprise', 'education'],
    accentId: 'sky',
    sources: ['arxiv', 'nasa_apod', 'reddit_space', 'quanta'],
    searchTerms: ['galaxy', 'exoplanet', 'telescope', 'cosmology', 'orbit'],
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'What other creatures do while we\'re not looking.',
    registers: ['awe', 'delight', 'warmth'],
    accentId: 'sage',
    sources: ['reddit_natureismetal', 'reddit_biology', 'inaturalist'],
    searchTerms: ['behavior', 'species', 'ecology', 'animal'],
  },
  {
    id: 'history',
    name: 'History',
    description: 'The footnotes that turn out to be the main story.',
    registers: ['surprise', 'awe', 'earned-discomfort'],
    accentId: 'rust',
    sources: ['wikipedia_top', 'wikipedia_onthisday', 'reddit_askhistorians'],
    searchTerms: ['discovered', 'forgotten', 'overlooked', 'untold'],
  },
  {
    id: 'archaeology',
    name: 'Archaeology',
    description: 'Digging up the things civilisations left behind.',
    registers: ['surprise', 'education', 'earned-discomfort'],
    accentId: 'rust',
    sources: ['wikipedia_top', 'wikipedia_onthisday', 'reddit_askhistorians'],
    searchTerms: ['excavation', 'ancient', 'artifact', 'ruins', 'civilization'],
  },
  {
    id: 'philosophy',
    name: 'Philosophy',
    description: 'The questions that refuse to be answered.',
    registers: ['education', 'awe', 'earned-discomfort'],
    accentId: 'plum',
    sources: ['aeon', 'reddit_philosophy', 'marginalian'],
    searchTerms: ['consciousness', 'ethics', 'existence', 'truth', 'paradox'],
  },
  // ── Human ingenuity ────────────────────────────────────────────
  {
    id: 'tech',
    name: 'Tech',
    description: 'What people are building and what it might mean.',
    registers: ['surprise', 'education', 'delight'],
    accentId: 'sky',
    sources: ['hackernews', 'reddit_dataisbeautiful', 'reddit_architecture'],
    searchTerms: ['software', 'startup', 'open source', 'systems', 'hardware'],
  },
  {
    id: 'ai',
    name: 'AI',
    description: 'The strange thing we\'re building and what it\'s showing us about ourselves.',
    registers: ['awe', 'surprise', 'education'],
    accentId: 'sky',
    sources: ['arxiv', 'hackernews', 'reddit_machinelearning'],
    searchTerms: ['model', 'language', 'neural', 'agent', 'intelligence'],
  },
  {
    id: 'design',
    name: 'Design',
    description: 'The decisions behind everything that looks effortless.',
    registers: ['awe', 'inspiration'],
    accentId: 'plum',
    sources: ['reddit_architecture', 'aeon', 'longreads'],
    searchTerms: ['craft', 'typography', 'architecture', 'interface', 'visual'],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    description: 'How things that shouldn\'t work somehow do.',
    registers: ['awe', 'education'],
    accentId: 'sky',
    sources: ['hackernews', 'phys_org', 'reddit_dataisbeautiful'],
    searchTerms: ['infrastructure', 'mechanism', 'build', 'structure', 'material'],
  },
  {
    id: 'medicine',
    name: 'Medicine',
    description: 'What the body is doing and what we\'re learning to do about it.',
    registers: ['education', 'awe', 'earned-discomfort'],
    accentId: 'sage',
    sources: ['phys_org', 'quanta', 'reddit_askscience'],
    searchTerms: ['treatment', 'disease', 'drug', 'clinical', 'biology'],
  },
  // ── Mind & meaning ─────────────────────────────────────────────
  {
    id: 'psychology',
    name: 'Psychology',
    description: 'Why we do what we do and usually get it wrong.',
    registers: ['education', 'surprise', 'warmth'],
    accentId: 'plum',
    sources: ['aeon', 'marginalian', 'reddit_askscience'],
    searchTerms: ['bias', 'cognition', 'behavior', 'perception', 'memory'],
  },
  {
    id: 'neuroscience',
    name: 'Neuroscience',
    description: 'The brain watching itself try to understand itself.',
    registers: ['awe', 'education', 'surprise'],
    accentId: 'plum',
    sources: ['quanta', 'phys_org', 'reddit_askscience'],
    searchTerms: ['neuron', 'consciousness', 'brain', 'cognition', 'neural'],
  },
  {
    id: 'language',
    name: 'Language',
    description: 'Words carry the fingerprints of the people who first needed them.',
    registers: ['surprise', 'delight', 'education'],
    accentId: 'plum',
    sources: ['reddit_etymology', 'wikipedia_onthisday', 'aeon'],
    searchTerms: ['etymology', 'word', 'language', 'meaning', 'origin'],
  },
  {
    id: 'creativity',
    name: 'Creativity',
    description: 'How great things actually get made.',
    registers: ['inspiration', 'awe', 'warmth'],
    accentId: 'rose',
    sources: ['reddit_writing', 'lithub', 'longreads', 'aeon'],
    searchTerms: ['process', 'craft', 'making', 'artist', 'creative'],
  },
  // ── Money & systems ────────────────────────────────────────────
  {
    id: 'finance',
    name: 'Finance',
    description: 'Markets, money, and the stories we tell about both.',
    registers: ['surprise', 'education'],
    accentId: 'mustard',
    sources: ['reddit_wsb', 'reddit_economics', 'hackernews'],
    searchTerms: ['market', 'stock', 'rate', 'fund', 'trading'],
  },
  {
    id: 'economics',
    name: 'Economics',
    description: 'The invisible systems that shape everyday life.',
    registers: ['education', 'earned-discomfort'],
    accentId: 'mustard',
    sources: ['reddit_economics', 'aeon', 'longreads'],
    searchTerms: ['economy', 'inequality', 'growth', 'policy', 'wealth'],
  },
  {
    id: 'business',
    name: 'Business',
    description: 'What actually happens inside companies and why.',
    registers: ['education', 'surprise'],
    accentId: 'mustard',
    sources: ['hackernews', 'reddit_economics'],
    searchTerms: ['startup', 'company', 'strategy', 'industry', 'founder'],
  },
  {
    id: 'markets',
    name: 'Markets',
    description: 'The weird and wonderful corners of financial markets.',
    registers: ['surprise', 'delight'],
    accentId: 'mustard',
    sources: ['reddit_wsb', 'reddit_dataisbeautiful', 'reddit_economics'],
    searchTerms: ['stock', 'trading', 'volatility', 'indicator', 'chart'],
  },
  // ── Culture & joy ──────────────────────────────────────────────
  {
    id: 'comedy',
    name: 'Comedy',
    description: 'Jokes, bits, and the architecture of laughter.',
    registers: ['delight', 'surprise', 'warmth'],
    accentId: 'mustard',
    sources: ['reddit_standup', 'reddit_writingprompts', 'reddit_til'],
    searchTerms: ['joke structure', 'comedian', 'satire', 'wit'],
  },
  {
    id: 'music',
    name: 'Music',
    description: 'Where sound does things words can\'t.',
    registers: ['delight', 'warmth', 'inspiration'],
    accentId: 'rose',
    sources: ['reddit_til', 'longreads', 'lithub'],
    searchTerms: ['album', 'musician', 'genre', 'song', 'concert'],
  },
  {
    id: 'film',
    name: 'Film',
    description: 'What cinema is actually doing when it moves you.',
    registers: ['delight', 'education', 'inspiration'],
    accentId: 'rose',
    sources: ['reddit_movies', 'longreads', 'lithub'],
    searchTerms: ['director', 'cinematography', 'screenplay', 'scene'],
  },
  {
    id: 'literature',
    name: 'Literature',
    description: 'Books and the people who couldn\'t stop writing them.',
    registers: ['warmth', 'inspiration', 'education'],
    accentId: 'rose',
    sources: ['reddit_books', 'lithub', 'marginalian', 'longreads'],
    searchTerms: ['novel', 'author', 'writing', 'story', 'poetry'],
  },
  {
    id: 'sports',
    name: 'Sports',
    description: 'The numbers and stories behind athletic achievement.',
    registers: ['surprise', 'delight'],
    accentId: 'plum',
    sources: ['reddit_til', 'reddit_dataisbeautiful'],
    searchTerms: ['athlete', 'record', 'strategy', 'performance', 'match'],
  },
  {
    id: 'food',
    name: 'Food',
    description: 'The history, science, and culture hiding in every meal.',
    registers: ['delight', 'warmth', 'surprise'],
    accentId: 'sage',
    sources: ['reddit_til', 'reddit_damnthatsinteresting', 'inaturalist'],
    searchTerms: ['ingredient', 'recipe', 'cuisine', 'fermentation', 'flavor'],
  },
  // ── World & people ─────────────────────────────────────────────
  {
    id: 'geopolitics',
    name: 'Geopolitics',
    description: 'Why borders, power, and geography shape everything.',
    registers: ['education', 'earned-discomfort'],
    accentId: 'rust',
    sources: ['reddit_askhistorians', 'aeon', 'longreads'],
    searchTerms: ['power', 'conflict', 'diplomacy', 'nation', 'region'],
  },
  {
    id: 'culture',
    name: 'Culture',
    description: 'The ideas, rituals, and habits that bind us together.',
    registers: ['warmth', 'surprise', 'education'],
    accentId: 'plum',
    sources: ['reddit_til', 'aeon', 'marginalian'],
    searchTerms: ['tradition', 'ritual', 'society', 'identity', 'shift'],
  },
  {
    id: 'biography',
    name: 'Biography',
    description: 'The private lives that shaped the public record.',
    registers: ['warmth', 'inspiration', 'awe'],
    accentId: 'rust',
    sources: ['wikipedia_onthisday', 'longreads', 'lithub'],
    searchTerms: ['life', 'person', 'story', 'career', 'legacy'],
  },
  {
    id: 'oddities',
    name: 'Oddities',
    description: 'Things that shouldn\'t exist but somehow do.',
    registers: ['surprise', 'delight', 'awe'],
    accentId: 'plum',
    sources: ['reddit_til', 'reddit_damnthatsinteresting', 'wikipedia_unusual'],
    searchTerms: [],
  },
];

export function getTopicById(id: TopicId): Topic | undefined {
  return TOPICS.find(t => t.id === id);
}

export function getAllTopics(): Topic[] {
  return TOPICS;
}
